name: Build and dep

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy Html
      run: cp -a dist/jatri-app/browser/index.html dist/jatri-app/browser/404.html

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: dist/jatri-app/browser
        enable_jekyll: true